import { sendVirtualKey } from './virtual-keyboard';
import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';

test('SSH config aliases, remote folders and terminal from a mobile browser', async ({ page }) => {
  const info = JSON.parse(readFileSync('.data/browser-test-info.json', 'utf8'));
  const token = readFileSync(info.tokenFile, 'utf8').trim();
  mkdirSync('.data/screenshots', { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('Connection key', { exact: true }).fill(token);
  await page.getByRole('button', { name: 'Connect', exact: true }).click();
  await page.getByRole('button', { name: 'More', exact: true }).click();
  await page.getByRole('button', { name: 'Manage SSH hosts' }).click();
  await expect(page.locator('.host-alias')).toHaveCount(4);
  await expect(page.getByRole('button', { name: 'included-alias', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/ssh-aliases-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'included-alias', exact: true }).click();
  await expect(page.getByLabel('SSH target')).toHaveValue('included-alias');
  await page.getByRole('button', { name: 'Check connection', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('SSH and tmux verified');
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Open projects and sessions' }).click();
  await page.getByRole('button', { name: 'Add project', exact: true }).first().click();
  await expect(page.getByLabel('Project server').locator('option[value="alias:jelly-remote"]')).toHaveCount(1);
  await page.getByLabel('Project server').selectOption('alias:jelly-remote');
  await expect(page.getByLabel('Project server')).toHaveValue(/^[a-f0-9-]{36}$/);
  await page.getByRole('button', { name: 'Browse' }).click();
  // The home path belongs to the SSH container, not the Jelly server.
  await expect(page.locator('.directory-selection strong')).toHaveText('/root');
  await page.getByRole('button', { name: 'Parent', exact: true }).click();
  await page.getByRole('region', { name: 'Server folders' }).getByRole('button', { name: 'workspaces', exact: true }).click();
  await page.getByRole('region', { name: 'Server folders' }).getByRole('button', { name: 'remote-project', exact: true }).click();
  await page.getByRole('button', { name: 'Select this folder' }).click();
  await expect(page.getByLabel('Server folder path')).toHaveValue('/workspaces/remote-project');
  await page.getByLabel('Project name').fill('SSH Projects');
  await page.getByRole('dialog').getByRole('button', { name: 'Add project', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: 'Open projects and sessions' }).click();
  await page.getByRole('button', { name: 'New session', exact: true }).click();
  await page.getByLabel('Session name').fill('원격 작업');
  await page.getByRole('button', { name: 'Open session', exact: true }).click();
  await expect(page.locator('.connection-label')).toHaveText('Connected', { timeout: 15_000 });
  await page.getByRole('button', { name: 'Show draft input', exact: true }).click();
  await page.getByLabel('Command or message').fill("printf '\\nBROWSER_SSH_%s\\n' OK; pwd");
  await page.getByRole('button', { name: 'Send input' }).click();
  await sendVirtualKey(page, 'Enter');
  await page.getByRole('button', { name: 'History', exact: true }).click();
  await expect(page.locator('.history-content')).toContainText('BROWSER_SSH_OK');
  await expect(page.locator('.history-content')).toContainText('/workspaces/remote-project');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.screenshot({ path: '.data/screenshots/ssh-terminal-mobile.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.connection-label')).toHaveText('Connected', { timeout: 15_000 });
  const inputField = page.getByRole('textbox', { name: 'Input', exact: true });
  await inputField.fill("printf '\\nINPUT_SSH_%s\\n' '");
  const cdp = await page.context().newCDPSession(page);
  try {
    for (const text of ['ㅎ', '하', '한', '한ㄱ', '한그', '한글']) {
      await cdp.send('Input.imeSetComposition', { text, selectionStart: text.length, selectionEnd: text.length });
    }
    await cdp.send('Input.insertText', { text: '한글' });
    await inputField.pressSequentially("'");
    await inputField.press('Enter');
    await expect(page.locator('.xterm-rows')).toContainText('INPUT_SSH_한글');
  } finally { await cdp.detach(); }
  await page.getByRole('button', { name: 'More', exact: true }).click();
  await page.getByRole('button', { name: 'Stop session', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Stop session', exact: true }).click();
  await expect(page.getByText('Session ended')).toBeVisible();
  await page.getByRole('button', { name: 'Open projects and sessions' }).click();
  await page.getByRole('button', { name: 'Remove record for 원격 작업' }).click();
  await page.getByRole('button', { name: 'Open projects and sessions' }).click();
  await page.getByRole('button', { name: 'More', exact: true }).click();
  await page.getByRole('button', { name: 'Remove project', exact: true }).click();
  await page.getByRole('button', { name: 'Remove from list', exact: true }).click();
  await page.getByRole('button', { name: 'More', exact: true }).click();
  await page.getByRole('button', { name: 'Manage SSH hosts' }).click();
  await page.getByRole('button', { name: 'Remove host jelly-remote' }).click();
  await expect(page.locator('.host-row')).toHaveCount(0);
  expect(errors).toEqual([]);
});
