import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';

test('SSH config aliases, remote folders and terminal from a mobile browser', async ({ page }) => {
  const info = JSON.parse(readFileSync('.data/browser-test-info.json', 'utf8'));
  const token = readFileSync(info.tokenFile, 'utf8').trim();
  mkdirSync('.data/screenshots', { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await page.getByLabel('연결 키', { exact: true }).fill(token);
  await page.getByRole('button', { name: '연결', exact: true }).click();
  await page.getByRole('button', { name: '더 보기', exact: true }).click();
  await page.getByRole('button', { name: 'SSH 서버 관리' }).click();
  await expect(page.locator('.host-alias')).toHaveCount(4);
  await expect(page.getByRole('button', { name: 'included-alias', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/ssh-aliases-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'included-alias', exact: true }).click();
  await expect(page.getByLabel('SSH 접속 대상')).toHaveValue('included-alias');
  await page.getByRole('button', { name: '연결 확인', exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('SSH·tmux 연결 확인 완료');
  await page.getByRole('button', { name: '돌아가기', exact: true }).click();
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '프로젝트와 세션 열기' }).click();
  await page.getByRole('button', { name: '프로젝트 추가', exact: true }).first().click();
  await expect(page.getByLabel('프로젝트 서버').locator('option[value="alias:jelly-remote"]')).toHaveCount(1);
  await page.getByLabel('프로젝트 서버').selectOption('alias:jelly-remote');
  await expect(page.getByLabel('프로젝트 서버')).toHaveValue(/^[a-f0-9-]{36}$/);
  await page.getByRole('button', { name: '폴더 찾기' }).click();
  // The home path belongs to the SSH container, not the Jelly server.
  await expect(page.locator('.directory-selection strong')).toHaveText('/root');
  await page.getByRole('button', { name: '상위', exact: true }).click();
  await page.getByRole('region', { name: '서버 폴더 목록' }).getByRole('button', { name: 'workspaces', exact: true }).click();
  await page.getByRole('region', { name: '서버 폴더 목록' }).getByRole('button', { name: 'remote-project', exact: true }).click();
  await page.getByRole('button', { name: '이 폴더 선택' }).click();
  await expect(page.getByLabel('서버 폴더 경로')).toHaveValue('/workspaces/remote-project');
  await page.getByLabel('프로젝트 이름').fill('SSH 프로젝트');
  await page.getByRole('dialog').getByRole('button', { name: '프로젝트 추가', exact: true }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await page.getByRole('button', { name: '프로젝트와 세션 열기' }).click();
  await page.getByRole('button', { name: '새 세션 열기', exact: true }).click();
  await page.getByLabel('세션 이름').fill('원격 작업');
  await page.getByRole('button', { name: '세션 열기', exact: true }).click();
  await expect(page.locator('.connection-label')).toHaveText('연결됨', { timeout: 15_000 });
  await page.getByRole('button', { name: '입력창 표시', exact: true }).click();
  await page.getByLabel('명령어 또는 메시지').fill("printf '\\nBROWSER_SSH_%s\\n' OK; pwd");
  await page.getByRole('button', { name: '입력 보내기' }).click();
  await page.getByRole('button', { name: 'Enter', exact: true }).click();
  await page.getByRole('button', { name: '기록', exact: true }).click();
  await expect(page.locator('.history-content')).toContainText('BROWSER_SSH_OK');
  await expect(page.locator('.history-content')).toContainText('/workspaces/remote-project');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.screenshot({ path: '.data/screenshots/ssh-terminal-mobile.png', fullPage: true });
  await page.reload();
  await expect(page.locator('.connection-label')).toHaveText('연결됨', { timeout: 15_000 });
  await page.getByRole('button', { name: '더 보기', exact: true }).click();
  await page.getByRole('button', { name: '세션 종료', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '세션 종료', exact: true }).click();
  await expect(page.getByText('세션 종료됨')).toBeVisible();
  await page.getByRole('button', { name: '프로젝트와 세션 열기' }).click();
  await page.getByRole('button', { name: '원격 작업 기록 삭제' }).click();
  await page.getByRole('button', { name: '프로젝트와 세션 열기' }).click();
  await page.getByRole('button', { name: '더 보기', exact: true }).click();
  await page.getByRole('button', { name: '프로젝트 삭제', exact: true }).click();
  await page.getByRole('button', { name: '목록에서 삭제', exact: true }).click();
  await page.getByRole('button', { name: '더 보기', exact: true }).click();
  await page.getByRole('button', { name: 'SSH 서버 관리' }).click();
  await page.getByRole('button', { name: 'jelly-remote 서버 삭제' }).click();
  await expect(page.locator('.host-row')).toHaveCount(0);
  expect(errors).toEqual([]);
});
