import { sendVirtualKey } from './virtual-keyboard';
import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';

test('desktop and mobile: login, projects, terminal input, history, reconnect and stop', async ({ page, browser }) => {
  const info = JSON.parse(readFileSync('.data/browser-test-info.json', 'utf8'));
  const token = readFileSync(info.tokenFile, 'utf8').trim();
  mkdirSync('.data/screenshots', { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Connect to server' })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/login-desktop.png', fullPage: true });
  await page.getByLabel('Connection key', { exact: true }).fill('wrong-key');
  await page.getByRole('button', { name: 'Connect', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Invalid connection key.');
  await page.getByLabel('Connection key', { exact: true }).fill(token);
  await page.getByRole('button', { name: 'Connect', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'No projects', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Add project', exact: true }).last().click();
  await page.getByLabel('Project name').fill('Jelly');
  await page.getByRole('button', { name: 'Browse' }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(homedir());
  await page.getByRole('button', { name: 'Enter path' }).click();
  await page.getByLabel('Folder path', { exact: true }).fill(info.browseRoot);
  await page.getByRole('button', { name: 'Go', exact: true }).click();
  const folders = page.getByRole('region', { name: 'Server folders' });
  await expect(folders.getByRole('button', { name: 'project', exact: true })).toBeVisible();
  await expect(folders.getByRole('button', { name: '.hidden-folder', exact: true })).toHaveCount(0);
  await expect(folders.getByText('notes.txt')).toHaveCount(0);
  await page.getByLabel('Hidden folders', { exact: true }).check();
  await expect(folders.getByRole('button', { name: '.hidden-folder', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/directory-desktop.png', fullPage: true });
  await page.getByLabel('Search folders').fill('project');
  await expect(folders.getByRole('button')).toHaveCount(1);
  await folders.getByRole('button', { name: 'project', exact: true }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await expect(folders.getByText('No subfolders')).toBeVisible();
  await page.getByRole('button', { name: 'Parent', exact: true }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.browseRoot);
  await folders.getByRole('button', { name: 'project', exact: true }).click();
  await page.getByRole('button', { name: 'Select this folder' }).click();
  await expect(page.getByLabel('Server folder path')).toHaveValue(info.projectPath);
  await expect(page.getByLabel('Project name')).toHaveValue('Jelly');
  // Reopening starts at the selected directory; failed navigation and cancellation preserve the form.
  await page.getByRole('button', { name: 'Browse' }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await page.getByRole('button', { name: 'Enter path' }).click();
  await page.getByLabel('Folder path', { exact: true }).fill(info.browseRoot + '/missing');
  await page.getByLabel('Folder path', { exact: true }).press('Enter');
  await expect(page.getByRole('alert')).toContainText('Folder not found.');
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await page.getByRole('button', { name: 'Back', exact: true }).click();
  await expect(page.getByLabel('Server folder path')).toHaveValue(info.projectPath);
  await page.getByRole('dialog').getByRole('button', { name: 'Add project', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Select a session', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/workspace-empty.png', fullPage: true });
  await page.getByRole('button', { name: 'New session', exact: true }).click();
  await page.getByLabel('Session name').fill('첫 번째 작업');
  await page.getByRole('button', { name: 'Open session', exact: true }).click();
  await expect(page.locator('.connection-label')).toHaveText('Connected');
  await page.getByRole('textbox', { name: 'Input', exact: true }).focus();
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill("printf '\\nJELLY_%s\\n' WEB_OK");
  await sendVirtualKey(page, 'Enter');
  await page.getByRole('button', { name: 'History', exact: true }).click();
  await expect(page.locator('.history-content')).toContainText('JELLY_WEB_OK');
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'More', exact: true }).click();
  await page.getByRole('button', { name: 'Disconnect', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Disconnected', exact: true })).toBeVisible();
  await page.locator('.connection-overlay').getByRole('button', { name: 'Reconnect' }).click();
  await expect(page.locator('.connection-label')).toHaveText('Connected');
  await page.reload();
  await expect(page.locator('.connection-label')).toHaveText('Connected');
  await page.screenshot({ path: '.data/screenshots/terminal-desktop.png', fullPage: true });

  // Browser language does not change Jelly's English UI or Unicode input support.
  const mobileContext = await browser.newContext({ locale: 'ko-KR', viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto('/');
  await expect(mobile).toHaveTitle('Jelly');
  await expect(mobile.locator('html')).toHaveAttribute('lang', 'en');
  await mobile.screenshot({ path: '.data/screenshots/login-mobile.png', fullPage: true });
  await mobile.getByLabel('Connection key', { exact: true }).fill(token);
  await mobile.getByRole('button', { name: 'Connect', exact: true }).click();
  await mobile.getByRole('button', { name: 'Open projects and sessions' }).click();
  await mobile.getByRole('button', { name: 'Add project', exact: true }).click();
  await mobile.getByRole('button', { name: 'Browse' }).click();
  await expect(mobile.locator('.directory-selection strong')).toHaveText(homedir());
  await mobile.getByRole('button', { name: 'Enter path' }).click();
  await mobile.getByLabel('Folder path', { exact: true }).fill(info.browseRoot);
  await mobile.getByRole('button', { name: 'Go', exact: true }).click();
  await expect(mobile.locator('.directory-selection strong')).toHaveText(info.browseRoot);
  await mobile.screenshot({ path: '.data/screenshots/directory-mobile.png', fullPage: true });
  expect(await mobile.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await expect(mobile.getByRole('button', { name: 'Select this folder' })).toBeInViewport();
  await mobile.getByRole('region', { name: 'Server folders' }).getByRole('button', { name: '한글 작업 & #', exact: true }).click();
  await mobile.getByRole('button', { name: 'Select this folder' }).click();
  await expect(mobile.getByLabel('Project name')).toHaveValue('한글 작업 & #');
  await expect(mobile.getByLabel('Server folder path')).toHaveValue(info.browseRoot + '/한글 작업 & #');
  await mobile.getByRole('button', { name: 'Cancel', exact: true }).click();
  await mobile.getByRole('button', { name: /첫 번째 작업/ }).click();
  await expect(mobile.locator('.connection-label')).toHaveText('Connected');
  await expect(page.getByRole('heading', { name: 'In use on another device', exact: true })).toBeVisible();
  await mobile.getByRole('textbox', { name: 'Input', exact: true }).focus();
  const command = mobile.getByRole('textbox', { name: 'Input', exact: true });
  await command.fill("printf '\\n%s%s\\n' '한글' '입력확인'");
  await sendVirtualKey(mobile, 'Enter');
  await mobile.getByRole('button', { name: 'History', exact: true }).click();
  await expect(mobile.locator('.history-content')).toContainText('한글입력확인');
  await mobile.getByRole('button', { name: 'Close', exact: true }).click();
  await mobile.getByRole('button', { name: 'Open virtual keyboard', exact: true }).click();
  await mobile.getByLabel('Paste text').click();
  await mobile.getByLabel('Text to paste').fill("printf '\\nPASTE_%s\\n' OK");
  await mobile.getByRole('button', { name: 'Send to terminal' }).click();
  // An explicit Enter after paste preserves the terminal's normal bracketed paste behavior.
  await mobile.getByLabel('Terminal input', { exact: true }).press('Enter');
  await mobile.getByRole('button', { name: 'History', exact: true }).click();
  await expect(mobile.locator('.history-content')).toContainText('PASTE_OK');
  await mobile.getByRole('button', { name: 'Close', exact: true }).click();
  await mobile.getByRole('button', { name: 'Close virtual keyboard', exact: true }).click();
  await mobile.getByRole('button', { name: 'Dismiss keyboard', exact: true }).click();
  await mobile.screenshot({ path: '.data/screenshots/terminal-mobile.png', fullPage: true });
  // The terminal begins immediately under a single 56px header on a phone.
  await expect(mobile.locator('header')).toHaveCount(1);
  expect((await mobile.locator('.workspace-header').boundingBox())!.height).toBe(56);
  expect((await mobile.locator('.terminal-stage').boundingBox())!.y).toBe(56);
  await expect(mobile.locator('.project-bar, .terminal-toolbar')).toHaveCount(0);
  await mobile.getByRole('button', { name: 'More', exact: true }).click();
  await expect(mobile.getByRole('region', { name: 'Session menu' })).toContainText(info.projectPath);
  await mobile.screenshot({ path: '.data/screenshots/header-menu-mobile.png', fullPage: true });
  await mobile.keyboard.press('Escape');
  await expect(mobile.getByRole('region', { name: 'Session menu' })).not.toBeVisible();
  await expect(mobile.getByRole('button', { name: 'More', exact: true })).toBeFocused();
  // The disclosure is keyboard operable and closes when tapping elsewhere.
  await mobile.keyboard.press('Enter');
  await expect(mobile.getByRole('region', { name: 'Session menu' })).toBeVisible();
  await mobile.locator('.workspace-heading').click();
  await expect(mobile.getByRole('region', { name: 'Session menu' })).not.toBeVisible();
  expect(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await mobile.setViewportSize({ width: 320, height: 568 });
  await expect(mobile.getByRole('button', { name: 'More', exact: true })).toBeInViewport();
  await expect(mobile.getByRole('button', { name: 'History', exact: true })).toBeInViewport();
  expect(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await mobile.setViewportSize({ width: 390, height: 520 });
  await mobile.getByRole('textbox', { name: 'Input', exact: true }).focus();
  await expect(mobile.getByRole('textbox', { name: 'Input', exact: true })).toBeInViewport();
  await expect(mobile.getByRole('button', { name: 'Open virtual keyboard', exact: true })).toBeInViewport();
  await mobile.getByRole('button', { name: 'More', exact: true }).click();
  await mobile.getByRole('button', { name: 'Stop session', exact: true }).click();
  await mobile.getByRole('dialog').getByRole('button', { name: 'Stop session', exact: true }).click();
  await expect(mobile.getByText('Session ended')).toBeVisible();
  await mobileContext.close();
  expect(errors).toEqual([]);
});
