import { test, expect } from '@playwright/test';
import { readFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';

test('desktop and mobile: login, projects, terminal input, history, reconnect and stop', async ({ page, browser }) => {
  const info = JSON.parse(readFileSync('.data/browser-test-info.json', 'utf8'));
  const token = readFileSync(info.tokenFile, 'utf8').trim();
  mkdirSync('.data/screenshots', { recursive: true });
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: '서버 연결' })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/login-desktop.png', fullPage: true });
  await page.getByLabel('연결 키', { exact: true }).fill('wrong-key');
  await page.getByRole('button', { name: '연결', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('연결 키가 올바르지 않습니다.');
  await page.getByLabel('연결 키', { exact: true }).fill(token);
  await page.getByRole('button', { name: '연결', exact: true }).click();
  await expect(page.getByRole('heading', { name: '프로젝트 없음', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '프로젝트 추가', exact: true }).last().click();
  await page.getByLabel('프로젝트 이름').fill('줼리');
  await page.getByRole('button', { name: '폴더 찾기' }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(homedir());
  await page.getByRole('button', { name: '경로 입력' }).click();
  await page.getByLabel('이동할 폴더 경로').fill(info.browseRoot);
  await page.getByRole('button', { name: '이동', exact: true }).click();
  const folders = page.getByRole('region', { name: '서버 폴더 목록' });
  await expect(folders.getByRole('button', { name: 'project', exact: true })).toBeVisible();
  await expect(folders.getByRole('button', { name: '.hidden-folder', exact: true })).toHaveCount(0);
  await expect(folders.getByText('notes.txt')).toHaveCount(0);
  await page.getByLabel('숨김 폴더', { exact: true }).check();
  await expect(folders.getByRole('button', { name: '.hidden-folder', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/directory-desktop.png', fullPage: true });
  await page.getByLabel('폴더 이름 검색').fill('project');
  await expect(folders.getByRole('button')).toHaveCount(1);
  await folders.getByRole('button', { name: 'project', exact: true }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await expect(folders.getByText('하위 폴더 없음')).toBeVisible();
  await page.getByRole('button', { name: '상위', exact: true }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.browseRoot);
  await folders.getByRole('button', { name: 'project', exact: true }).click();
  await page.getByRole('button', { name: '이 폴더 선택' }).click();
  await expect(page.getByLabel('서버 폴더 경로')).toHaveValue(info.projectPath);
  await expect(page.getByLabel('프로젝트 이름')).toHaveValue('줼리');
  // Reopening starts at the selected directory; failed navigation and cancellation preserve the form.
  await page.getByRole('button', { name: '폴더 찾기' }).click();
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await page.getByRole('button', { name: '경로 입력' }).click();
  await page.getByLabel('이동할 폴더 경로').fill(info.browseRoot + '/missing');
  await page.getByLabel('이동할 폴더 경로').press('Enter');
  await expect(page.getByRole('alert')).toContainText('폴더를 찾을 수 없습니다.');
  await expect(page.locator('.directory-selection strong')).toHaveText(info.projectPath);
  await page.getByRole('button', { name: '돌아가기', exact: true }).click();
  await expect(page.getByLabel('서버 폴더 경로')).toHaveValue(info.projectPath);
  await page.getByRole('dialog').getByRole('button', { name: '프로젝트 추가', exact: true }).click();
  await expect(page.getByRole('heading', { name: '세션 선택', exact: true })).toBeVisible();
  await page.screenshot({ path: '.data/screenshots/workspace-empty.png', fullPage: true });
  await page.getByRole('button', { name: '새 세션 열기', exact: true }).click();
  await page.getByLabel('세션 이름').fill('첫 번째 작업');
  await page.getByRole('button', { name: '세션 열기', exact: true }).click();
  await expect(page.locator('.connection-label')).toHaveText('연결됨');
  await page.getByRole('button', { name: '입력창 표시' }).click();
  await page.getByLabel('명령어 또는 메시지').fill("printf '\\nJELLY_%s\\n' WEB_OK");
  await page.getByRole('button', { name: '입력 보내기' }).click();
  await page.getByRole('button', { name: 'Enter', exact: true }).click();
  await page.getByRole('button', { name: '기록', exact: true }).click();
  await expect(page.locator('.history-content')).toContainText('JELLY_WEB_OK');
  await page.getByRole('button', { name: '닫기', exact: true }).click();
  await page.getByRole('button', { name: '더 보기', exact: true }).click();
  await page.getByRole('button', { name: '연결 끊기', exact: true }).click();
  await expect(page.getByRole('heading', { name: '연결 끊김', exact: true })).toBeVisible();
  await page.locator('.connection-overlay').getByRole('button', { name: '다시 연결' }).click();
  await expect(page.locator('.connection-label')).toHaveText('연결됨');
  await page.reload();
  await expect(page.locator('.connection-label')).toHaveText('연결됨');
  await page.screenshot({ path: '.data/screenshots/terminal-desktop.png', fullPage: true });

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 });
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto('/');
  await mobile.screenshot({ path: '.data/screenshots/login-mobile.png', fullPage: true });
  await mobile.getByLabel('연결 키', { exact: true }).fill(token);
  await mobile.getByRole('button', { name: '연결', exact: true }).click();
  await mobile.getByRole('button', { name: '프로젝트와 세션 열기' }).click();
  await mobile.getByRole('button', { name: '프로젝트 추가', exact: true }).click();
  await mobile.getByRole('button', { name: '폴더 찾기' }).click();
  await expect(mobile.locator('.directory-selection strong')).toHaveText(homedir());
  await mobile.getByRole('button', { name: '경로 입력' }).click();
  await mobile.getByLabel('이동할 폴더 경로').fill(info.browseRoot);
  await mobile.getByRole('button', { name: '이동', exact: true }).click();
  await expect(mobile.locator('.directory-selection strong')).toHaveText(info.browseRoot);
  await mobile.screenshot({ path: '.data/screenshots/directory-mobile.png', fullPage: true });
  expect(await mobile.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await expect(mobile.getByRole('button', { name: '이 폴더 선택' })).toBeInViewport();
  await mobile.getByRole('region', { name: '서버 폴더 목록' }).getByRole('button', { name: '한글 작업 & #', exact: true }).click();
  await mobile.getByRole('button', { name: '이 폴더 선택' }).click();
  await expect(mobile.getByLabel('프로젝트 이름')).toHaveValue('한글 작업 & #');
  await expect(mobile.getByLabel('서버 폴더 경로')).toHaveValue(info.browseRoot + '/한글 작업 & #');
  await mobile.getByRole('button', { name: '취소', exact: true }).click();
  await mobile.getByRole('button', { name: /첫 번째 작업/ }).click();
  await expect(mobile.locator('.connection-label')).toHaveText('연결됨');
  await expect(page.getByRole('heading', { name: '다른 기기에서 접속 중', exact: true })).toBeVisible();
  await mobile.getByRole('button', { name: '입력창 표시', exact: true }).click();
  const command = mobile.getByLabel('명령어 또는 메시지');
  await command.fill("printf '\\n%s%s\\n' '한글' '입력확인'");
  await mobile.getByRole('button', { name: '입력 보내기' }).click();
  await mobile.getByRole('button', { name: 'Enter', exact: true }).tap();
  await mobile.getByRole('button', { name: '기록', exact: true }).click();
  await expect(mobile.locator('.history-content')).toContainText('한글입력확인');
  await mobile.getByRole('button', { name: '닫기', exact: true }).click();
  await mobile.getByRole('button', { name: '보조 키 더 보기', exact: true }).click();
  await mobile.getByLabel('텍스트 붙여넣기').click();
  await mobile.getByLabel('붙여넣을 텍스트').fill("printf '\\nPASTE_%s\\n' OK");
  await mobile.getByRole('button', { name: '터미널로 보내기' }).click();
  // An explicit Enter after paste preserves the terminal's normal bracketed paste behavior.
  await mobile.getByLabel('터미널 입력', { exact: true }).press('Enter');
  await mobile.getByRole('button', { name: '기록', exact: true }).click();
  await expect(mobile.locator('.history-content')).toContainText('PASTE_OK');
  await mobile.getByRole('button', { name: '닫기', exact: true }).click();
  await mobile.getByRole('button', { name: '보조 키 접기', exact: true }).click();
  await mobile.getByRole('button', { name: '입력창 숨기기', exact: true }).click();
  await mobile.screenshot({ path: '.data/screenshots/terminal-mobile.png', fullPage: true });
  // The terminal begins immediately under a single 56px header on a phone.
  await expect(mobile.locator('header')).toHaveCount(1);
  expect((await mobile.locator('.workspace-header').boundingBox())!.height).toBe(56);
  expect((await mobile.locator('.terminal-stage').boundingBox())!.y).toBe(56);
  await expect(mobile.locator('.project-bar, .terminal-toolbar')).toHaveCount(0);
  await mobile.getByRole('button', { name: '더 보기', exact: true }).click();
  await expect(mobile.getByRole('region', { name: '작업 메뉴' })).toContainText(info.projectPath);
  await mobile.screenshot({ path: '.data/screenshots/header-menu-mobile.png', fullPage: true });
  await mobile.keyboard.press('Escape');
  await expect(mobile.getByRole('region', { name: '작업 메뉴' })).not.toBeVisible();
  await expect(mobile.getByRole('button', { name: '더 보기', exact: true })).toBeFocused();
  // The disclosure is keyboard operable and closes when tapping elsewhere.
  await mobile.keyboard.press('Enter');
  await expect(mobile.getByRole('region', { name: '작업 메뉴' })).toBeVisible();
  await mobile.locator('.workspace-heading').click();
  await expect(mobile.getByRole('region', { name: '작업 메뉴' })).not.toBeVisible();
  expect(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await mobile.setViewportSize({ width: 320, height: 568 });
  await expect(mobile.getByRole('button', { name: '더 보기', exact: true })).toBeInViewport();
  await expect(mobile.getByRole('button', { name: '기록', exact: true })).toBeInViewport();
  expect(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await mobile.setViewportSize({ width: 390, height: 520 });
  await mobile.getByRole('button', { name: '입력창 표시', exact: true }).click();
  await expect(mobile.getByRole('button', { name: '입력 보내기' })).toBeInViewport();
  await expect(mobile.getByRole('button', { name: 'Esc', exact: true })).toBeInViewport();
  await mobile.getByRole('button', { name: '더 보기', exact: true }).click();
  await mobile.getByRole('button', { name: '세션 종료', exact: true }).click();
  await mobile.getByRole('dialog').getByRole('button', { name: '세션 종료', exact: true }).click();
  await expect(mobile.getByText('세션 종료됨')).toBeVisible();
  await mobileContext.close();
  expect(errors).toEqual([]);
});
